services:
  benchmark:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - CHRYSALIS_REPO
        - CHRYSALIS_SHA
        - UPLC_TURBO_REPO
        - UPLC_TURBO_SHA
        - PLUTIGO_REPO
        - PLUTIGO_SHA
        - BLAZE_REPO
        - BLAZE_SHA
        - PLUTUZ_REPO
        - PLUTUZ_SHA
        - OPSHIN_REPO
        - OPSHIN_SHA
        - HASKELL_REPO
        - HASKELL_SHA
        - SCALUS_REPO
        - SCALUS_SHA
        - ZIG_VERSION
        - GHC_VERSION
    cap_add:
      - SYS_NICE
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    volumes:
      - ./results:/results
